<?php

namespace PubsBundle\Repository;

/**
 * requetteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class requetteRepository extends \Doctrine\ORM\EntityRepository
{
    public function findUpdateSignall($id,$iduser){
        $query = $this->getEntityManager()
            ->createQuery("update PubsBundle:Publications p set p.signall=concat(concat(p.signall,:iduser),',')  WHERE (p.id=:id)")
            ->setParameters(array('id'=>$id,'iduser'=>$iduser)); //très important! parameterS
        return $query->getResult();
    }
    public function findNbr($id)
    {
        $query = $this->getEntityManager()
            ->createQuery("select p.signall from PubsBundle:Publications p  WHERE (p.id=:id)")
            ->setParameter('id',$id); //très important! parameterS
        return substr_count($query->getResult()[0]["signall"],',');
    }
    public function countpub($t)
   {
       $query=$this->getEntityManager()
           ->createQuery("select p.signall from PubsBundle:Publications p where (p.type =:typee)")
           ->setParameter('typee',$t); //très important! parameterS
       return $query->getResult();

}


}
