<?php

namespace AdoptBundle\Repository;

/**
 * PetRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PetRepository extends \Doctrine\ORM\EntityRepository
{
    public function findInsultes($comment){
        $query = $this->getEntityManager()
            ->createQuery("select i from AdoptBundle:Insult i WHERE i.insult=:comment")
            ->setParameter('comment', $comment);
        return $query->getResult();
    }

    public function idcheap(){
        $query = $this->getEntityManager()
            ->createQuery("SELECT t.idPet FROM AdoptBundle:Pet t ORDER BY t.idPet ");
        return $query->getResult();
    }

    public function findticket($e2){
        $query = $this->getEntityManager()
            ->createQuery("select f from AdoptBundle:Petrecup f WHERE f.namePet LIKE '%".$e2."%'");

        return $query->getResult();
    }

    public function findByPostId($postid){
        $query = $this->getEntityManager()
            ->createQuery("select b from AdoptBundle:Comments b WHERE b.postid=:postid")
            ->setParameter('postid', $postid);
        return $query->getResult();
    }

    public function findTinder(){
        $query = $this->getEntityManager()
            ->createQuery("SELECT o FROM AdoptBundle:Pet o WHERE NOT EXISTS (SELECT s.idPet FROM AdoptBundle:Matching s WHERE o.idPet = s.idPet)");
            //->createQuery("SELECT o FROM AdoptBundle:Pet o WHERE NOT EXISTS (SELECT s FROM AdoptBundle:Matching WHERE o = s.idPet)");
        return $query->getResult();
    }

    public function findMatched($id){
        $query = $this->getEntityManager()
            ->createQuery("SELECT o FROM AdoptBundle:Pet o WHERE EXISTS (SELECT s.idPet FROM AdoptBundle:Matching s WHERE s.idUser=:id)")
            ->setParameter('id', $id);
        //->createQuery("SELECT o FROM AdoptBundle:Pet o WHERE NOT EXISTS (SELECT s FROM AdoptBundle:Matching WHERE o = s.idPet)");
        return $query->getResult();
    }


}


//SELECT * FROM pet WHERE id_pet IN (SELECT id_pet FROM matching  WHERE id_user=1)