<?php

namespace AdoptBundle\Repository;

/**
 * testsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class testsRepository extends \Doctrine\ORM\EntityRepository
{

}
