shop_homepage:
    path:     /
    defaults: { _controller: ShopBundle:Default:index }

shop_home:
    path:     /home
    defaults: { _controller: ShopBundle:Default:Layout }

shop_store:
    path:     /shop
    defaults: { _controller: ShopBundle:Produit:Produits }

shop_cart:
    path:     /cart
    defaults: { _controller: ShopBundle:Panier:AddProduct }

addCartAjax:
    path:     /cartAjax/{id}
    defaults: { _controller: ShopBundle:Panier:AddProductAjax }


shop_cart_show:
    path:     /cart_show
    defaults: { _controller: ShopBundle:Panier:AfficherPanier }

shop_produit:
    path:     /produit_detail
    defaults: { _controller: ShopBundle:Produit:ProduitDetail }

CartAffich:
    path:     /AfficherCart
    defaults: { _controller: ShopBundle:Produit:AfficherCart }

Delete_Produit:
    path:     /DeleteProduit{id}
    defaults: { _controller: ShopBundle:Panier:delete }


AddCommande:
    path:     /commande
    defaults: { _controller: ShopBundle:Panier:AddOrder }