<?php

namespace PubsBundle\Repository;

/**
 * insultesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class insultesRepository extends \Doctrine\ORM\EntityRepository
{
    public function findInsultes($comment)
    {
        $query = $this->getEntityManager()
            ->createQuery("select i from PubsBundle:insultes i WHERE i.chaine=:comment")
            ->setParameter('comment', $comment); //ma3andekch mochkla maa schema update enti maw? donc t'ajouti el table manuellement?ouii barra ajouti table esmha insultes nemchi ena? lel chromeokkkk
        return $query->getResult();
    }
}
