<?php

namespace PubsBundle\Repository;
use PubsBundle\Entity\Publications;

/**
 * PublicationsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PublicationsRepository extends \Doctrine\ORM\EntityRepository
{
    public function getpub()
    {
        $query=$this->getEntityManager()
            ->createQuery("select u.username,p.id,p.image,p.date,p.type,p.time,p.description from PubsBundle:Publications p LEFT JOIN UserBundle:User u WHERE p.iduser = u.id");
//            ->setParameter('id',$t); //très important! parameterS
        return $query->getResult();

    }
    public function getonepub($id)
    {
        $query=$this->getEntityManager()
            ->createQuery("select u.username,p.id,p.image,p.date,p.type,p.time,p.description,p.iduser from PubsBundle:Publications p LEFT JOIN UserBundle:User u WHERE p.iduser = u.id WHERE p.id=:id")
            ->setParameter('id',$id); //très important! parameterS
        return $query->getResult();

    }

    public function getidd(){
        $query=$this->getEntityManager()
            ->createQuery("select u.id from UserBundle:User u " );
        return $query->getResult();

    }
    public function getmaxpub($id){
        $query=$this->getEntityManager()
            ->createQuery("select p.id from PubsBundle:publications p where p.iduser=:idd")
            ->setParameter('idd',$id);
        return count($query->getResult());
    }


}
