<?php

namespace ShopBundle\Repository;

/**
 * TestRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TestRepository extends \Doctrine\ORM\EntityRepository
{
    public function findProductParameterDQL($id)
    {
        $query=$this->getEntityManager()->createQuery("select m from ShopBundle:Panier m WHERE m.idUser=:id")->setParameter('iduser',$id);
        return $query->getResult();
    }
}
