<?php

namespace ShopBundle\Repository;

/**
 * commRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class commRepository extends \Doctrine\ORM\EntityRepository
{
}
