<?php

namespace ShopBundle\Repository;

/**
 * TestRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TestRepository extends \Doctrine\ORM\EntityRepository
{
    public function findProductParameterDQL($id)
    {
        $query=$this->getEntityManager()->createQuery("select m from ShopBundle:Panier m WHERE m.iduser=:id and m.etat=:etat")->setParameters(array('id'=>$id,'etat'=>0));
        return $query->getResult();
    }

    public function findProductUser($u,$p)
    {
        $q=$this->getEntityManager()->createQuery("select c from ShopBundle:Panier c where c.idProduit=:p and c.iduser=:u and c.etat=:etat")
            ->setParameter('u',$u)
            ->setParameter('p',$p)
            ->setParameter('etat',0);
        return $q->getResult();

    }

    public function rate($id)
    {
        $q=$this->getEntityManager()->createQuery("select AVG(c.rating) from ShopBundle:Rate c where c.idpr=:id")
            ->setParameter('id',$id);
        return $q->getResult();

    }


    public function affiche(){
        $q=$this->getEntityManager()->createQuery("select a.idproduit,a.nomproduit,a.description,a.prix,a.quantite,a.imageproduit,IDENTITY(a.idcategorie),a.nomraceproduit,IDENTITY(a.idboutiqueproduit),a.promotion,a.taux,Avg(c.rating) as rate from ShopBundle:Produit a left join ShopBundle:Rate c WITH (a.idproduit=c.idpr) GROUP BY a.idproduit
");
        return $q->getResult();
    }

    public function filter($u,$p)
    {
        $q=$this->getEntityManager()->createQuery("select c from ShopBundle:Produit c where c.idcategorie=:p AND c.idboutiqueproduit=:u")
            ->setParameter('u',$u)
            ->setParameter('p',$p);
        return $q->getResult();

    }
}
