<?php

namespace VetsBundle\Repository;

/**
 * TestVetRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TestVetRepository extends \Doctrine\ORM\EntityRepository
{
    public function findBudget($id){
        $query = $this->getEntityManager()
            ->createQuery("select i.consultation,i.vaccinationchat,i.vaccinationchien,i.analyses,i.sterilisation from VetsBundle:Tarif i where i.idVeto=:id")
            ->setParameter('id',$id);
        return $query->getResult();
    }
    public function findRdv($id){
        $query = $this->getEntityManager()
            ->createQuery("select i.heure,i.dateRdv from VetsBundle:Rdv i where i.idVeto=:id")
            ->setParameter('id',$id);
        return $query->getResult();
    }

}
